_instantiator:
    value: lightning.pytorch.cli.instantiate_module
_wandb:
    value:
        cli_version: 0.19.10
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
        python_version: 3.12.13
        t:
            "1":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 12
                - 41
                - 49
                - 51
                - 53
                - 55
                - 63
                - 71
                - 105
                - 106
            "2":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 12
                - 41
                - 49
                - 51
                - 53
                - 55
                - 63
                - 71
                - 105
                - 106
            "3":
                - 7
                - 13
                - 23
                - 55
                - 66
            "4": 3.12.13
            "5": 0.19.10
            "6": 4.56.1
            "8":
                - 1
                - 5
                - 12
            "12": 0.19.10
            "13": linux-x86_64
attn_mask_annealing_enabled:
    value: false
attn_mask_annealing_end_steps:
    value: null
attn_mask_annealing_start_steps:
    value: null
ckpt_path:
    value: /content/drive/MyDrive/FAIML_project_and_presentation/01_Project/large_files/weights/eomt_coco.bin
class_coefficient:
    value: 2
class_only_loss:
    value: false
delta_weights:
    value: false
dice_coefficient:
    value: 5
freeze_all_except_class_head:
    value: false
freeze_encoder:
    value: false
freeze_encoder_except_last_n:
    value: 1
head_only_no_grad:
    value: false
ignore_idx:
    value: 255
img_size:
    value:
        - 1024
        - 1024
importance_sample_ratio:
    value: 0.75
llrd:
    value: 0.8
llrd_l2_enabled:
    value: true
load_ckpt_class_head:
    value: false
lr:
    value: 1e-05
lr_mult:
    value: 1
mask_coefficient:
    value: 5
mask_thresh:
    value: 0.8
network:
    value:
        class_path: models.eomt_finetuning.EoMT
        init_args:
            encoder:
                class_path: models.vit.ViT
                init_args:
                    backbone_name: vit_base_patch14_reg4_dinov2
                    patch_size: 16
            masked_attn_enabled: false
            num_blocks: 3
            num_q: 200
no_object_coefficient:
    value: 0.1
num_classes:
    value: 19
num_points:
    value: 2048
overlap_thresh:
    value: 0.8
oversample_ratio:
    value: 3
poly_power:
    value: 0.9
use_cached_backbone_tokens:
    value: true
use_cached_features:
    value: false
warmup_steps:
    value:
        - 500
        - 1000
weight_decay:
    value: 0.05
